- .travis.yml
- R/onload.R
- R/utils.R
- man/add_xml_data.Rd
- man/create_xml.Rd
- man/run_xml_conversion.Rd
- tests/testthat/test_xml_conv_utils.R
Adds a global option gcamdata.use_java (default to FALSE) that controls if `run_xml_conversion` and any of the tests that rely on it are actually run so they can be safely skipped if a user does not have Java installed.
This resolves #103
> Java optional

- R/utils-data.R
Addresses #289 . This commit is dedicated to @cahartin
> Ensure no line breaks in object comments

- R/pipeline-helpers.R
- tests/testthat/test_pipeline-helpers.R
> Fix behavior of left_join_keep_first_only using named 'by' vector.

- R/zchunk_L242.Bld_Inc_Elas_scenarios.R
- R/zchunk_L252.Trn_Inc_Elas_scenarios.R
Apparently, whether this is a bug or not depends on exactly what package versions you have installed.  I'd say the best practice is to avoid using `$` in arguments to dplyr functions that use NSE.
> Fix bad interaction between dplyr NSE and data frame $ indexing.

- .travis.yml
This should prevent us from timing out while running the package tests.
As with the after_success script, the timeout defaults to 20 minutes, but can be increased by adding an additional argument to travis_wait (e.g. `travis_wait 30 R CMD check *.tar.gz`)
> Add travis_wait to the R CMD check step of the CI process.

- R/zchunk_LA101.en_bal_IEA.R
- R/zchunk_LA118.hydro.R
- R/zchunk_LA121.oil.R
The chunks that may (or may not, depending on IEA data being present)
prebuilt outputs now always include these prebuilts as precursors. This
eliminates the red warning messages during a driver run, messages that
might obscure/confuse.
> Remove precursor warning messages

- R/zchunk_batch_bld_agg_xml.R
- R/zchunk_batch_trn_agg_xml.R
This fixes some of the missing XML files noted in #620, still no GCAM3 inputs files.  Was that a conscious decision to leave out?
Perhaps the bld / trn socioeconomic files should have been implemented in a loop which could have avoided the inadvertent SSP instead gSSP bug.  @d3y419 can clean that up if he so chooses.
> Fix inadvertent SSP3/5 that should have been gSSP3/5 in bld and trn scio xml.

- R/module-helpers.R
- R/zchunk_L141.hfc_R_S_T_Y.R
- R/zchunk_LA143.HDDCDD.R
since otherwise we get package check errors with dplyr 0.5 about not package rlang.  In the long term we can come up with a better solution. See #677
> Revert to using the deprecated nesting_ for dplyr 0.7

- R/xml.R
- tests/testthat/test_xml_conv_utils.R
Switch to using system2 instead of pipe for running the CSVToXML Java process despite the performance hit since pipe wasn't behaving correctly on Windows anyhow.  As a added bonus this also closes #102.
> Switch to using system2 instead of pipe for running the CSVToXML Java

- R/zchunk_L110.water.demand.primary.R
- R/zchunk_LA108.ag_Feed_R_C_Y.R
complete from tidyr 0.8.0 passes along observations that are grouped by a variable with a value of NA. This fix removes NA before complete is called so that the resulting data frames pass the old new tests. 
Addresses #858
> tidyr_update

- R/zchunk_batch_Cstorage_USA_xml.R
- R/zchunk_batch_Fert_USA_xml.R
This PR removes the `dummy-logit-tags` from the gcam usa module xmls.
> Fix gcam usa dummy logit tags

- R/driver.R
- R/onload.R
- R/utils.R
- man/driver.Rd
- man/save_chunkdata.Rd
While incorporating gcamdata into the GCAM it became obvious we probably want to change the default behavior of the package to write the XML files as that is what we need to run GCAM.  It also occurs to me that the most common use case is to just build the XML files and skip CSVs so I thought it would be handy to be able to configure the driver to run that way (and add an `xml` target to the GCAM Makefile to call the driver that way).
Change the default for use_java to TRUE.
Split the driver option of writing outputs to be able to control if CSV is output or XML is output separately.
> Change XML options

- R/zchunk_batch_land_input_4_IRR_MGMT_xml.R
Remove extra land_node_rename in XML pipeline for land_input_4_IRR_MGMT which doesn't affect the substance of the XML in terms of GCAM input but just generates a lot of extra LandNode tags.
Note this won't change comparison data as it effects the XML file.  It also doesn't affect anything in terms of substance, the old version just had an extra `land_node_rename()` the end result of which call which just extra LandNode XML tags and in different order:
```
WE34383:server2 pralitp$ sort xml/land_input_4_IRR_MGMT.xml | grep -v LandNode > new.txt 
WE34383:server2 pralitp$ vi new.txt 
WE34383:server2 pralitp$ sort ~/model/gcam-core-git/input/gcamdata/xml/land_input_4_IRR_MGMT.xml | grep -v LandNode > old.txt 
WE34383:server2 pralitp$ diff -q old.txt new.txt 
WE34383:server2 pralitp$ 
```
> OLDNEW aglu_batch_land_input_4_IRR_MGMT XML

- R/zchunk_L2233.electricity_water.R
Fix failing join due to year mismatch causing tech interpolation rules to not get copied.
This only affects one data product:
```
1/2 mismatches
[1] 0 - 9 == -9
Dimensions are not the same for L2233.GlobalTechInterp_elec_cool.csv
Incompatible type for column `from.year`: x character, y numeric
Incompatible type for column `to.year`: x character, y numeric
L2233.GlobalTechInterp_elec_cool.csv doesn't match
```
Note that in the old data system no rows were produced so a statistical comparison is not valid.  However we can see the …
> OLDNEW for L2233.electricity_water

- R/zchunk_L241.fgas.R
Having to do with not droping technologies for which input emissions were zero for all years.
Seems to affect a couple of other data products not directly related:
```
1/2 mismatches
[1] 16947 - 2807 == 14140
Dimensions are not the same for L241.fgas_all_units.csv
Different number of rows
L241.fgas_all_units.csv doesn't match
3. Failure: matches old data system output (@test_oldnew.R#102) ----------------
1/2 mismatches
[1] 15488 - 1348 == 14140
Dimensions are not the same for …
```
> OLDNEW for L241.fgas

- R/zchunk_L243.bio_trade_input.R
No longer repeat use.trial.market flag 32 times just to match the old data system.
This only affects one data product exactly as we expect, going from 32 rows to 1:
```
1/2 mismatches
[1] 32 - 1 == 31
Dimensions are not the same for L243.SectorUseTrialMarket_Bio.csv
Different number of rows
L243.SectorUseTrialMarket_Bio.csv doesn't match
```
> OLDNEW for L243.bio_trade_input

- R/zchunk_L210.resources.R
Fix subset which was meant to select only one grade by region.  The numbers do not change, just the values get repeated more than they need to be.
This directly affects the geothermal maxSubResource for regular and EGS sub resources and also affects the GCAM-USA geothermal resource:
```
1/2 mismatches
[1] 64 - 32 == 32
Dimensions are not the same for L210.GrdRenewRsrcMax_EGS.csv
Different number of rows
L210.GrdRenewRsrcMax_EGS.csv doesn't match
3. Failure: matches old data system output (@test_oldnew.R#102) ---------------- …
```
> OLDNEW for L210.resources

- R/zchunk_L244.building_USA.R
- inst/extdata/gcam-usa/A44.demand_satiation_mult.csv
Using the wrong year for floorspace(first instead of last) when calculating per floorspace building service satiation level.
Note taking care of this exposes another bug (#979) which gets fixed here too.
This effects two data products as we expect:
```
1. Failure: matches old data system output (@test_oldnew.R#115) ----------------
Rows in x but not y: 261, 353, 128, 506, 183, 616, 631, 281, 195, 419, 270[...]. Rows in y but not x: 662, 660, 659, 656, 654, 653, 651, 649, 648, 644, 643[...].
L244.GenericServiceSatiation_gcamusa.csv doesn't match
Rows in x but not y: 204, 203, 202, 200, 199, 198, 197, …
```
> OLDNEW fixes for L244.building_USA

- R/zchunk_L110.water.demand.primary.R
This code changes two files: `L110.water_demand_primary_R_S_W_m3_GJ` and `L210.TechCoef`. The changes are small in absolute value but large in percentage change. They are all changes to the Middle East, which used to be given the coefficients for USA, but now use their own calculated values.
> OLDNEW - L110.water.demand.primary

- R/zchunk_LA119.solar-gcam-usa.R
Calculating averages rather than taking values from input file leads to fairly small differences.
> OLDNEW for LA119.Solar

- R/zchunk_LB134.Diet_Rfao.R
Having to do with starting a loop with the wrong "prev_year" (last model year instead of last historical year).
The upshot is we get the "wrong' income elasticities in the first future year in the SSPs.  From the statistical comparison it seems some of these can be significant.
```
Rows in x but not y: 3420, 3419, 3418, 3413, 3412, 3411, 3410, 3409, 3407, 3406, 3124[...]. Rows in y but not x: 3418, 3416, 3415, 3410, 3409, 3407, 3406, 3405, 3125, 3123, 3121[...]. 
L134.pcFood_kcald_R_Dmnd_Y_ssp1.csv doesn't match
Rows in x …
```
> OLDNEW for LB134.Diet_Rfao

- R/zchunk_L123.bcoc_awb_R_S_T_Y.R
Having to do with matching first the first value instead of aggregating all.
It affects the following data outputs:
```
Rows in x but not y: 6252, 6236, 6232, 6226, 6222, 6192, 6188, 6178, 6170, 6166, 6160[...]. Rows in y but not x: 6236, 6232, 6222, 6214, 6210, 6204, 6200, 6192, 6178, 6170, 6166[...]. 
L123.bcoc_tgmt_R_awb_2000.csv doesn't match
Rows in x but not y: 25008, 25007, 25005, 24976, 24975, 24974, 24973, 24928, 24927, 24925, 24904[...]. Rows in y but not x: 25008, 25006, 25005, 24976, 24944, 24942, 24927, …
```
> OLDNEW for L123.bcoc_awb_R_S_T_Y

- R/zchunk_L124.nonco2_unmgd_R_S_T_Y.R
This one is pretty ugly. The changes in the code keep EDGAR emissions that shouldn't have been deleted. This includes various gases from some regions and NH3 for all regions.
26 files are changes. All of them have new rows. Some have changed values as well. The value changes are sometimes fairly large in terms of percentages. Most of the extremely large changes are dealing with very small absolute changes.
Files changed:
L124.deforest_coefs,
L124.nonco2_tg_R_forest_Y_GLU,
L124.nonco2_tg_R_grass_Y_GLU,
L212.AgSupplySector,
L212.AgSupplySubsector,
L212.FORESTEmissions_D_noprot,
L212.FORESTEmissions_D_prot,
L212.FORESTEmissions_D,
L212.FORESTEmissions_FF_noprot,
L212.FORESTEmissions_FF_prot,
L212.FORESTEmissions_FF,
L212.FORESTEmissionsFactors_BCOC_D_noprot, …
> OLDNEW-L124.nonco2_unmgd_R_S_T_Y

- R/zchunk_L112.ghg_en_R_S_T_Y.R
Having to do with a join that should have included the technology.
This only affects a few data products:
```
Rows in x but not y: 139574, 139572, 139570, 139569, 139566, 139565, 139562, 139561, 139560, 139559, 139554[...]. Rows in y but not x: 139571, 139570, 139569, 139567, 139565, 139560, 139554, 139552, 139549, 139547, 139345[...]. 
L112.ghg_tg_R_en_S_F_Yh.csv doesn't match
Rows in x but not y: 141702, 141701, 141697, 141692, 141691, 141689, 141688, 141686, 141684, 141682, 141680[...]. Rows in y but not x: 141699, …
```
> OLDNEW for L112.ghg_en_R_S_T_Y

- R/zchunk_LA144.Commercial.R
Having to do with a state to 4-region census division mapping that was wrong in the old data system.
This only affects a couple of data products:
```
Rows in x but not y: 758, 316, 70, 197, 18, 238, 367, 401, 707, 279, 14[...]. Rows in y but not x: 764, 731, 724, 707, 678, 672, 622, 595, 578, 575, 554[...]. 
L144.flsp_bm2_state_comm.csv doesn't match
Rows in x but not y: 248, 238, 229, 218, 223. Rows in y but not x: 248, 238, 223, 218, 229. 
L244.Floorspace_gcamusa.csv doesn't match
```
And the differences are small: …
> OLDNEW for LA144.Commercial; 

- R/zchunk_L102.ghg_en_USA_S_T_Y.R
Having to do with a join that should have included technology but didn't.
Closely related data products are affected:
```
Rows in x but not y: 26, 25, 18, 11. Rows in y but not x: 26, 25, 18, 11. 
L102.ghg_tgej_USA_en_Sepa_F_2005.csv doesn't match
Rows in x but not y: 139612, 139609, 139608, 139604, 139599, 139598, 139597, 139594, 139593, 139592, 139574[...]. Rows in y but not x: 139612, 139608, 139607, 139603, 139602, 139601, 139599, 139598, 139597, 139596, 139595[...]. 
L112.ghg_tg_R_en_S_F_Yh.csv doesn't match
3. …
```
> OLDNEW for L102.ghg_en_USA_S_T_Y.R

- R/zchunk_L103.ghg_an_USA_S_T_Y.R
Having to do with not ignoring NA values when summing poultry CH4 emissions factor thus resulting in zero emissions factor.
Directly related data products change:
```
Rows in x but not y: 4. Rows in y but not x: 4. 
L103.ghg_tgmt_USA_an_Sepa_F_2005.csv doesn't match
Rows in x but not y: 77798, 77758, 77694, 77486, 77212, 77210, 77204, 77202, 77196, 77194, 77188[...]. Rows in y but not x: 77574, 77440, 77438, 77376, 77204, 77194, 77188, 77180, 77172, 77162, 77154[...]. 
L113.ghg_tg_R_an_C_Sys_Fd_Yh.csv doesn't match
3. …
```
> OLDNEW for L103.ghg_an_USA_S_T_Y

- R/zchunk_L100.Population_downscale_ctry.R
Having to do with missing "Eritrea and Ethiopia" in the old ds population mapping file.
This affects a number of downstream data products mostly having to do with land cover:
```
Rows in x but not y: 10580, 10579, 10571, 10562, 10556, 10549, 10545, 10536, 10534, 10533, 10532[...]. Rows in y but not x: 10575, 10572, 10569, 10556, 10550, 10549, 10548, 10546, 10532, 10522, 10510[...]. 
L100.Pop_thous_ctry_Yh.csv doesn't match
Rows in x but not y: 1428, 1427, 1382, 1381, 1336, 1335, 1293, 1292, 1289, 1199, 1198[...]. Rows in …
```
> OLDNEW for L100.Population_downscale_ctry

- R/zchunk_L270.limits.R
- R/zchunk_batch_negative_emissions_budget_xml.R
- man/module_energy_L270.limits.Rd
- man/module_energy_batch_negative_emissions_budget_xml.Rd
splitting apart spa23 so 2 and 3 each have their own budgets.  This is
because while they should share policy assumptions the actual GDPs are
different which factors into the budget.
Note this will require a GCAM_DATA_MAP update at some point but I see a conflict 'a brewin so I've put it off for now until we omnibus.
This should remove the `L270.NegEmissBudget_spa23` data product and add `L270.NegEmissBudget_spa2` and `L270.NegEmissBudget_spa3`
> OLDNEW for L270.limits / Negative Emissions Budgets

- R/zchunk_LA143.HDDCDD.R
having to do with:
* Not dropping Cote 'dIvoire
* New method for weighted mean DD using population as weights
This changes a surprising number of data products:
```
Rows in x but not y: 2409, 2410, 2902. Rows in y but not x: 2902, 2410, 2409. 
L101.in_EJ_R_en_Si_F_Yh.csv doesn't match
Rows in x but not y: 311855, 54526, 54517, 33022, 14086, 26375, 59649, 54332, 54529, 14287, 59838[...]. Rows in y but not x: 311855, 59838, 59649, 54529, 54526, 54517, 54332, 53208, 40919, 33022, 14287[...]. 
L111.nonghg_tg_R_en_S_F_Yh.csv …
```
> OLDNEW for LA143.HDDCDD

- R/constants.R
- R/module-helpers.R
- R/zchunk_L222.land_input_2.R
- R/zchunk_L2231.land_input_3_irr.R
Reduce carbon contents of managed forest and pasture where the carbon content was not being properly reduced from the unmanged values.  The regression came somewhere in the merge of GCAM 4.4 changes into GCAM 5.  This closes #875.
Only direct data products are affected:
```
Rows in x but not y: 377, 376, 374, 372, 369, 368, 366, 365, 363, 362, 361[...]. Rows in y but not x: 378, 377, 375, 373, 371, 370, 369, 368, 366, 364, 363[...]. 
L222.LN2_MgdCarbon.csv doesn't match
Rows in x but not y: 336, 335, 331, 330, 328, 327, …
```
> Fix a regression of proposal 244

- DESCRIPTION
Update DESCRIPTION to point to the rebased version off of v1: JGCRI/gcamdata.compdata#17
> Update gcamdata.compdata pointer

- DESCRIPTION
Update DESCRIPTION to point to the rebased version off of v1: JGCRI/gcamdata.compdata#19
> Update gcamdata.compdata pointer for usa-emis-v1.0 branch

- R/xml.R
Fix bug in XML conversion utils where a spaces to any path used in theCSVToXML command (classpath, header file, output file) was not being
escaped and therefore failing.  This closes #1049
Also make the return values from the XML conversion pipeline utils be
`invisible()` to avoid unintentionally barfing tons of data.
> Bugfix spaces in XML conversion paths

- tests/testthat/test_oldnew.R
Add explicit check on if we have files in the outputs directory to make comparisons for the OLD/NEW tests and "skip" if not.
Note this helps pass tests on AppVeyor as we do not have it generate the outputs to do the test (only on Travis). AppVeyor runs into memory limits while trying to load `COMPDATA` which of course isn't necessary if we didn't have any outputs to compare anyways.
> Skip Old/New when no outputs
