R/driver.R
=> Simplify precursor check error message

R/DEMO_chunk_LA112.U.R, R/chunk_L100.GDP_hist.R, R/chunk_LA100.Socioeconomics.R, R/constants.R, R/sample-chunk.R, chunk-generator/chunk-generator.R, tests/testthat/test_oldnew.R
Addresses issue #43 , per @pralitp feedback
=> Clarify long year form flag

chunk-generator/sample-pattern.R
=> Add month and year to author field

R/zchunk_LA100.FAO_downscale_ctry.R
=> Have LA100.FAO_downscale_ctry product long data

R/driver.R
=> Disable capture.output

tests/testthat/test_graph_chunks.R
=> Make graph_chunks optional if no igraph

tests/testthat/test_oldnew.R
=> Run driver if on Travis

R/zchunk_LA100.FAO_downscale_ctry.R, tests/testthat/test_chunks.R
Check chunk code for forbidden calls
=> Forbiddens

chunk-generator/chunk-generator.R
=> Don't generate chunk skeletons for done chunks

R/zchunk_LB151.ag_MIRCA_ctry_C_GLU_irr.R
=> File for @kvcalvin

R/zchunk_L110.water.demand.primary.R, R/zchunk_LA100.GTAP_downscale_ctry.R, R/zchunk_LB111.ag_resbio_R_C.R, tests/testthat/test_oldnew.R
And removed unnecessary flags from chunks. Thanks @rynacui
=> Fixed FLAG_NO_XYEAR check

R/zchunk_LA143.HDDCDD.R
=> Russell-LA143.HDDCDD_fix

R/zchunk_batch_modeltime_xml.R, chunk-generator/chunk-generator.R
It looks like I didn't push this commit in time for the `xml` branch merge.
=> Avoid chunk names with .xml.R and instead make them _xml.R

R/zchunk_L102.ghg_en_USA_S_T_Y.R
https://github.com/JGCRI/gcamdata/issues/384
added header info
=> description and details added to header

R/zchunk_LB122.LC_R_Cropland_Yh_GLU.R
Speeds things up a ton, still passes Test Package and Check Package
=> Snyder_LB122_again per suggestion of RPL, added ungroup() to slow pipeline

R/module-helpers.R, man/get_logit_fn_tables.Rd, tests/testthat/test_module_helpers.R
=> Fix calls to write_to_all_regions from get_logit_fn_tables

.Rbuildignore, .gitattributes, README.md, appveyor.yml
=> Add appveyor support

R/utils.R, man/extract_header_info.Rd, tests/testthat/test_fileutil.R
=> Don't allow empty file header lines

R/xml.R, tests/testthat/test_xml_conv_utils.R
=> Assert `logit.type` is a column in the data for calls to

R/zchunk_L100.GDP_hist.R, man/module_socioeconomics_L100.GDP_hist.Rd
=> Fill in required chunk documentation

R/zchunk_L115.nh3_an_R_S_T_Y.R
Replaced unnecessary unite -> separate calls and removed unnecessary mutate calls.
Fixes #817
=> Kd_enhance_l115_nh3_an_r_s_t_y

inst/extdata/energy/A23.globaltech_capital.csv
Update documentation on A23 input file for electricity technology costs to refer to journal paper (verified with Gokul that this is the appropriate reference).
=> A23 doc update

R/module-helpers.R, R/zchunk_L222.en_transformation_USA.R, R/zchunk_L223.electricity_USA.R, R/zchunk_L2232.electricity_FERC_USA.R, R/zchunk_L2322.Fert_USA.R, R/zchunk_L261.carbon_storage_USA.R, R/zchunk_LA100.IEA_downscale_ctry.R
Second half of #897 list.
Closes #897
=> Prevent logit.type removal second half of 897

R/zchunk_LA100.FAO_downscale_ctry.R, man/module_aglu_LA100.FAO_downscale_ctry.Rd
=> Fill in LA100.FAO_downscale_ctry documentation

DESCRIPTION, tests/testthat/test_oldnew.R
Split out compdata into its own R package and load it in the old/new test as needed.
=> Split out compdata into its own package

R/zchunk_L2012.ag_For_Past_bio_input_irr_mgmt.R
Two changes:
1. Removed unused columns from L2012.AgProduction_ag_irr_mgmt.csv.
2. Added some rounding to an intermediate tibble, which didn't seem to have any downstream effect
=> OLDNEW-L2012.ag_For_Past

.travis.yml, R/zchunk_LB122.LC_R_Cropland_Yh_GLU.R
Removed two manual changes to match old data system. 
This changes values on a bunch of downstream files.
Changed files:
1. L122.ag_EcYield_kgm2_R_C_Y_GLU
2. L122.ag_HA_to_CropLand_R_Y_GLU
3. L122.EmissShare_R_C_Y_GLU
4. L122.ghg_tg_R_agr_C_Y_GLU
5. L122.LC_bm2_R_HarvCropLand_C_Yh_GLU
6. L122.LC_bm2_R_HarvCropLand_Yh_GLU
7. L122.LC_bm2_R_OtherArableLand_Yh_GLU
8. L1221.ghg_tg_R_agr_C_Y_GLU_IRR
9. L125.LC_bm2_R_LT_Yh_GLU
10. L131.LV_USD75_m2_R_GLU
11. L171.ag_irrEcYield_kgm2_R_C_Y_GLU
12. L171.ag_rfdEcYield_kgm2_R_C_Y_GLU
13. L171.LC_bm2_R_irrHarvCropLand_C_Yh_GLU
14. L171. LC_bm2_R_rfdHarvCropLand_C_Yh_GLU
15. L181.ag_EcYield_kgm2_R_C_Y_GLU_irr_level
16. L181.LC_bm2_R_C_Yh_GLU_irr_level
17. L2012.AgHAtoCL_irr_mgmt
18. L221.LN1_ValueLogit
19. L2231.LN3_HistUnmgdAllocation
20. …
=> OLDNEW-LB122.LC_R_Cropland_Yh_GLU

R/zchunk_L2042.resbio_input_irr_mgmt.R
Mil residue bio curves was using Forest price points instead of from it's own assumptions file.
It only affects the one data product:
```
1/2 mismatches
[1] 2728 - 60016 == -57288
Dimensions are not the same for L2042.StubResBioCurve_Mill.csv
Different number of rows
L2042.StubResBioCurve_Mill.csv doesn't match
```
Statistical differences are attached.
[diff_L2042.resbio_input_irr_mgmt.txt](https://github.com/JGCRI/gcamdata/files/2121708/diff_L2042.resbio_input_irr_mgmt.txt)
=> OLDNEW for L2042.resbio_input_irr_mgmt

R/zchunk_LA115.RooftopPV.R
2 changed files due to removal of manual data setting.
=> OLDNEW-LA115.RooftopPV

R/zchunk_L114.bcoc_en_R_S_T_Y.R
This changes 12 files. The absolute and percent differences are fairly small.
=> OLDNEW for L114.bcoc_en_R_S_T_Y

R/zchunk_LA154.Transport.R
Having to do with not taking into account mode before a merge.
This only affects a couple data products:
```
Rows in x but not y: 4079, 4077, 4073, 4059, 4057, 4053, 4051, 4049, 4041, 4039, 4033[...]. Rows in y but not x: 4076, 4073, 4067, 4065, 4062, 4060, 4053, 4049, 4042, 4035, 4022[...]. 
L154.out_mpkm_state_trn_nonmotor_Yh.csv doesn't match
Rows in x but not y: 403, 401, 399, 397, 395, 393, 391, 389, 387, 385, 383[...]. Rows in y but not x: 405, 401, 399, 395, 390, 388, 387, 381, 379, 369, 354[...]. …
```
=> OLDNEW for LA154.Transport

R/zchunk_LA144.Residential.R
Having to do with an aggregate which was aggregating the first service when there were multiple instead of all.
Just affects the GCAM-USA buildings service data products:
```
Rows in x but not y: 31555, 31503, 31457, 31453, 31452, 31442, 31439, 31429, 31426, 31402, 31388[...]. Rows in y but not x: 31555, 31508, 31504, 31503, 31486, 31439, 31435, 31429, 31421, 31401, 31386[...]. 
L144.in_EJ_state_res_F_U_Y.csv doesn't match
Rows in x but not y: 2633, 2541, 2533, 2377, 2333, 2321, 2221, 2177, 1241, 1385, 1865[...]. Rows in …
```
=> OLDNEW for LA144.Residential

R/zchunk_L100.Population_downscale_ctry.R, R/zchunk_L102.ghg_en_USA_S_T_Y.R, R/zchunk_L103.ghg_an_USA_S_T_Y.R
This includes #1010 #1011 #1013
=> Omnibus 1010 1011 1013

.travis.yml, DESCRIPTION
**NOTE**: we won't want this change when we finally merge to master.
=> Change the pacakge dependency to point to the "China" compdata branch.

R/constants.R
=> Remove duplicated constants. Closes #1032

DESCRIPTION, R/onload.R, data-raw/generate_package_data.R
=> Change to usethis::use_data because devtools version deprecated

R/Lu-L2231.electricity_nuclear_CHINA.R, R/Lu-zchunk_batch_electricity_nuclear_CHINA_xml.R
=> Revert "Revert "Updated_L2231.electricity_nuclear_CHINA_with_zchunk_batch""

R/Lu-zchunk_batch_en_prices_CHINA_xml.R, R/Lu_L226.en_distribution_CHINA.R
Create a variety of energy and electricity outputs for CHINA at the province and/or grid_region level.
=> L226.en_distribution_CHINA.R & zchunk_batch_en_prices_CHINA_xml.R

.gitignore, R/constants.R, R/zchunk_L231.proc_sector.R, tests/testthat/test_oldnew.R
=> replace all hard-coded numbers in L231

R/constants.R, R/zchunk_L243.bio_trade_input.R
=> remove hardcoded years

R/constants.R, R/zchunk_L241.fgas.R
Addressing #555 
Required major revision to complete calculations in long rather than wide format. Also tried to build in protection against timeshift - we shall see if it passes all tests
=> Remove hardcoded years in L241.fgas

tests/testthat/test_oldnew.R
checking to see if #1183 is fixed
=> remove fix for old_new

R/zchunk_L169.nonghg_NEI_scaling_USA.R, R/zchunk_LA125.hydrogen.R, R/zchunk_LB120.LC_GIS_R_LTgis_Yh_GLU.R
Fixed mutate calls that were for some reason caught by the coverage test but not the R-CMD
=> Coverage test

R/dstrace.R, R/graph.R, tests/testthat/test_dstrace.R
=> skip if no igraph
